module.exports = {
    HOME_PAGE_LOADED: 'HOME_PAGE_LOADED',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    SET_EDIT: 'SET_EDIT',
    SUBMIT_ARTICLE: 'SUBMIT_ARTICLE',
    EDIT_ARTICLE: 'EDIT_ARTICLE',
    HOST: 'localhost',
    PORT: 8000,
}